- demo/demo.md
- docs/design-notes.md
- docs/figma.md
- package-lock.json
**Fixes:** #7  (issue, if applicable)
Added design notes and Figma docs.
> docs(figma notes): add figma and design notes

- src/auro-combobox.js
**Fixes:** #29
Removes the functionality to pass the input value to menu on blur.
> fix(select): stop passing value to menu on input blur #29

- src/style.scss
Removed hover state background color change.
**Fixes:** #34  (issue, if applicable)
> fix(dropdown): remove hover state background color change #34

- apiExamples/noValidate.html
- demo/apiExamples.md
- docs/api.md
- docs/partials/apiExamples.md
- src/auro-combobox.js
**Fixes:** #37
Add the `noValidate` attribute which is passed down to auro-input.
Also adds documentation examples for the attribute.
-- …
> feat(noValidate): support auro-input noValidate attribute #37

- package-lock.json
- package.json
- src/auro-combobox.js
- test/auro-combobox.test.js
**Fixes:** #46
Adds all automated tests and some minor code fixes to make tests pass.
> fix(testing): add tests and fix code so they all pass #46

- apiExamples/noFilter.html
- demo/apiExamples.md
- docs/api.md
- docs/partials/apiExamples.md
- src/auro-combobox.js
- test/auro-combobox.test.js
**Fixes:** #50
This change is a significant rewrite of how combobox handles the menuoptions. It adds a new attribute to the API called `dynamicMenu`. If set, combobox will do no suggestion matching. All menuoptions in the DOM will be rendered. It is up to the developer using combobox with that attribute to dynamically insert only the menuoptions they need. Flight Search is using this connected to the citysearch API.
_Pull Requests will be evaluated by …
> fix(menu): updates to support dynamic menus #50

- demo/apiExamples.md
- src/auro-combobox.js
**Fixes:** #58
Add new attributes for use by peer dependencies
**Thank you for your submission!**
> Support dropdown matching width attribute for current release of dropdown

- src/auro-combobox.js
- test/auro-combobox.test.js
**Fixes:** #64 
* Add new event `auroMenu-selectValueReset`, causing `value` to be reset when event is fired.
* Add tests to ensure programmatically setting value to a valid value, invalid value and undefined work properly.
_Pull Requests will be evaluated by their quality of update and whether it …
> implement programmatic value reset

- apiExamples/value.js
**Fixes:** #66 
Update timeout of value example in `value.js`.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this …
> update timeout of value example

- README.md
- apiExamples/focus.js
- apiExamples/persistent.js
- apiExamples/value.js
- demo/api.html
- demo/apiExamples.md
- demo/examples.js
- package.json
- src/auro-combobox.js
**Fixes:** #69 
Makes auro-menu a direct dependency and refactors all examples per the new examples.js POC
> Refactor and fix all custom JS examples so they will work on the doc site

- src/style.scss
**Fixes:** #56 
Removed transparent background color when combobox is being hovered.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the …
> make background color consistent

- apiExamples/value.html
- demo/apiExamples.md
- docs/api.md
- package-lock.json
- src/auro-combobox.js
- test/auro-combobox.test.js
**Fixes:** #75
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your …
> fix(value): values correctly set programmatically #75

- src/style.scss
**Fixes:** #82 
Set the value of the min/max height of the input element to `--auro-size-700` , with `3.5rem` being the fallback value.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be …
> Make height consistent with all form elements

- apiExamples/persistent.html
- apiExamples/typeMonthDayYear.html
- demo/apiExamples.md
- demo/demo.md
- package-lock.json
- package.json
- src/auro-combobox.js
- test/auro-combobox.test.js
**Fixes:** #91 #93 #94 #97, #99
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to …
> Bug fixes per review of latest release

- src/style.scss
**Fixes:** #82 
Correct the positioning of the accent icon in `auro-input`, which was broken by the new release of `auro-input`.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a …
> Correct accent icon positioning

- package-lock.json
- package.json
- src/style.scss
**Fixes:** #104 
The last release of `auro-input` supports a conversion of using the `outline` css property to `box-shadow`. With that change, I unset input's `box-shadow` css property in `auro-combobox`.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with …
> Handle auro-input's new box-shadow css property

- apiExamples/dynamicMenu.html
- apiExamples/dynamicMenu.js
- apiExamples/dynamicMenuDataApi.js
- demo/api.js
- demo/api.md
- docs/partials/api.md
- package-lock.json
**Fixes:** #100 
Added an example to the demo page that dynamically loads the content into an `auro-combobox` every time a user types in the input.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is …
> Create dynamic menu example

- src/auro-combobox.js
**Fixes:** #115
Report `ready` for dynamic menus.
Show bib when typing on dynamic menus
> fix(menu): correct handling of empty dynamic menus #115

- .github/workflows/testPublish.yml
Changes to be committed:
modified:   .github/workflows/testPublish.yml
This PR will update the workflow dependencies. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a …
> Update pipeline dependencies

- rollup.config.js
**Fixes:** #138
Remove minification of example JS code
> perf(docs): remove minification of doc example js

- README.md
- apiExamples/dynamicMenu.js
- apiExamples/focus.js
- apiExamples/persistent.js
- apiExamples/swapValue.js
- apiExamples/value.js
- demo/api.html
- demo/api.js
- demo/api.md
- demo/index.html
- demo/index.js
- docTemplates/README.md
- package-lock.json
- package.json
**Fixes:** #140 
Refactor the initialization of the examples by exporting every example as a function and having a main parent function run all of the examples when the respective demo pages are loaded.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with …
> Refactor the initialization of examples

- README.md
- demo/api.html
- demo/index.html
- package.json
- scripts/prepExampleFiles.js
**Fixes:** #144
Adds a new script that modifies the bundler output for the two example scripts to strip the export from the end of the file.
**Thank you for your …
> perf(examples): modify the bundles created for the examples when running the build

- apiExamples/custom.html
- demo/index.html
- demo/index.md
- docs/partials/index.md
Add doc example for custom registration
> perf(docs): add example for custom registration

- demo/api.html
- demo/api.js
- demo/index.html
- demo/index.js
Change demo JS scripts to auto-execute on load
> perf(docs): fix demo JS examples

- demo/index.js
Add example logging and force a release build
> fix(examples): add logging messages and force build

- src/auro-combobox.js
The Flight Search Microsite saw an issue that occurred only in Android mobile devices.  The details can be seen here:
[Bug 1031663](https://itsals.visualstudio.com/E_Sell_Shop/_workitems/edit/1031663): Mobile Browser: Microsite CitySearch not populating results.
**Resolves:** #175 
_Pull Requests …
> Issue #175: added this.showBib() call to the input event

- .eslintrc
- eslint.config.mjs
- package-lock.json
- package.json
- src/auro-combobox.js
Updates dependencies to pull in a critical fix for auro-menu for SSR support. 
https://github.com/AlaskaAirlines/auro-menu/issues/208
-- …
> perf(deps): use latest version of auro-menu with SSR fix

- package-lock.json
**Resolves:** # (issue, if applicable)
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require …
> build: sync package-lock.json
